Update cs.po
nemaara/A_New_Order pull request #141
Opened 2023-08-24 21:04 UTC by MultiSeptim

Your turn @celerini...

2023-08-25 22:18 UTC, celerini requested changes
hm, you are hardworking, @MultiSeptim

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +msgstr "Ha, ha, lidský červy. Myslet, „vše co my nevzít“ bude vaše."
Řekl bych, že obecnou řeč nezdůrazní pravopisná chyba, která by se v řeči nepoznala. Ale možná se pletu.
```suggestion
msgstr "Ha, ha, lidský červi. Myslet, „vše co my nevzít“ bude vaše."
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"Tady jsem. Hlas mluvící k těm jež chtějí naslouchat. Vím, kdo jste a proč "
```suggestion
"Tady jsem. Hlas mluvící k těm, již chtějí naslouchat. Vím, kdo jste a proč "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"Zdá se, že režim ladění je buď zapnutý, nebo byl v minulosti zapnutý. Takže "
```suggestion
"Zdá se, že režim ladění je buď zapnutý, nebo byl zapnutý v minulosti. Takže "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"není jasné, zda se při zabití Bor Cryna podvádí nebo ne... pro jistotu je "
```suggestion
"není jasné, zda se při zabití Bor Cryna podvádí, nebo ne... pro jistotu je "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"Zdá se, že režim ladění je buď zapnutý, nebo byl v minulosti zapnutý. Takže "
```suggestion
"Zdá se, že režim ladění je buď zapnutý, nebo byl zapnutý v minulosti. Takže "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"není jasné, zda se pokoušíš zabít Bor Cryna podvodem nebo ne... pro jistotu "
```suggestion
"není jasné, zda se pokoušíš zabít Bor Cryna podvodem, nebo ne... pro jistotu "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"Zdá se, že režim ladění je buď zapnutý, nebo byl v minulosti zapnutý. Takže "
```suggestion
"Zdá se, že režim ladění je buď zapnutý, nebo byl zapnutý v minulosti. Takže "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"není jasné, zda se při zabití Uri van Roa podvádí nebo ne... pro jistotu je "
```suggestion
"není jasné, zda se při zabití Uri van Roa podvádí, nebo ne... pro jistotu je "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"Zdá se, že režim ladění je buď zapnutý, nebo byl v minulosti zapnutý. Takže "
```suggestion
"Zdá se, že režim ladění je buď zapnutý, nebo byl zapnutý v minulosti. Takže "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"není jasné, zda se pokoušíš zabít Uri van Roa podvodem nebo ne... pro "
```suggestion
"není jasné, zda se pokoušíš zabít Uri van Roa podvodem, nebo ne... pro "
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"slyšel by to udělat mohl – kdyby mohl myslet sám za sebe."
```suggestion
"slyšel, by to udělat mohl – kdyby mohl myslet sám za sebe."
```

2023-08-25 22:18 UTC, celerini commented on translations/wesnoth-A_New_Order/cs.po
> +"Hm, vypadá to, že je tu víc lidí, co to umí s kopím a lukem a šlo by je "
```suggestion
"Hm, vypadá to, že je tu víc lidí, co to umí s kopím a lukem, a šlo by je "
```

2023-08-27 14:53 UTC, MultiSeptim commented
Ready to merge.

2023-08-27 18:52 UTC, merged